# Generated by Django 3.1.7 on 2021-05-26 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_supplies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsupply',
            name='condition',
            field=models.CharField(blank=True, choices=[('BUILD', 'build'), ('SUPPLY', 'supply')], max_length=120, null=True),
        ),
    ]
